version: '3'

services:
  api:
    container_name: api
    build: .
    ports:
      - 5000:5000
    command: yarn docker:start
    volumes:
      - .:/usr/app
    environment:
      MONGO_URL: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017"
      PORT: 5000

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASS}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/"
